MWE-183 Cookie consent
molitio/molitio-web-engine pull request #28
Opened 2024-04-12 11:10 UTC by elliotscrubs

2024-04-12 15:07 UTC, vycos-zen commented
Build is failing, and recommendations where sent to refactor the imported component to be built by us.

2024-04-21 10:51 UTC, vycos-zen commented
the cookie consent react component still have some package dependencies missing that causes the build to fail. This is just removing the packages not needed, and they references. 

![image](https://github.com/molitio/molitio-web-engine/assets/8149214/745ad670-62e4-4fd9-919f-2df73e8b70ac)

2024-04-21 10:52 UTC, vycos-zen commented
the branch have merge conflicts with the main branch, those will need to be resolved. main merged -> MWE-183

2024-04-21 10:58 UTC, vycos-zen requested changes
Looks good, we have to make the build pass, and fix few minor findings. Great Work

2024-04-21 10:58 UTC, vycos-zen commented on packages/.nest/gql/schema.graphql
needs to bee removed. bad build command. will be fixed on a different branch

2024-04-21 10:58 UTC, vycos-zen commented on packages/john-glenn/app/components/consent/CookieConsentPopup.tsx
> +      : null
please use the [Fragment React](https://react.dev/reference/react/Fragment) component instead of null

2024-04-21 10:58 UTC, vycos-zen commented on packages/john-glenn/app/layout.tsx
> +import CookieConsentPopup from './components/consent/CookieConsentPopup';
should be

`import { CookieConsentPopup } from './components';`

Exports and "barrel" files will also have to be adjusted

2024-04-21 10:58 UTC, vycos-zen commented on packages/john-glenn/package.json
> +        "react-cookie-consent": "9.0.0",
Is this needed for the new version? It is ok if yes, just clarifying

2024-04-23 08:48 UTC, elliotscrubs commented on packages/john-glenn/app/components/consent/CookieConsentPopup.tsx
> +      : null
done

2024-05-20 15:24 UTC, vycos-zen commented on apps-api/.nest/gql/schema.graphql
delete this file please, it is cleaned up in other branches. it was generated here by error

2024-05-20 15:24 UTC, vycos-zen commented on apps-ui/john-glenn-ui/app/components/actions.js
For TypeScript we use .ts / .tsx file extensions. .tsx is for components in the ui. other functionalities use .ts extension

2024-05-20 15:24 UTC, vycos-zen commented on apps-ui/john-glenn-ui/app/components/consent/CookieConsentPopup.js
> +  const actions = useSelector(state => state.actions);
the name of the variable is too generic. it should express the intent, like setCookieAction

2024-05-20 15:24 UTC, vycos-zen commented on apps-ui/john-glenn-ui/app/components/consent/CookieConsentPopup.js
> +  const dispatch = useDispatch();
should be in line 7, on the top of the function

2024-05-20 15:24 UTC, vycos-zen commented on apps-ui/john-glenn-ui/app/components/index.js
> +const allReducers = combineReducers({
this should be in a separate file, not the index

2024-05-20 15:24 UTC, vycos-zen commented on apps-ui/john-glenn-ui/tsconfig.json
>          "../../.artifacts/john-glenn//types/**/*.ts"
double //

2024-05-20 15:24 UTC, vycos-zen commented on apps-ui/john-glenn-ui/tsconfig.json
> +, "app/components/consent/CookieConsentPopup.js"    ],
remove js file extension, and replace with .ts, .tsx

2024-06-11 16:03 UTC, vycos-zen commented
merged as main is already 74 commits ahead

2024-06-11 16:03 UTC, merged